[package]
name = "ballista-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ballista = "0.6"
datafusion = "6.0"
tokio = "1.0"
proc-macro2 = "=1.0.26"